import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css"
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";
import GlobalHooks from "./hook/useRoutesPrivacy/GlobalHooks";
import Head from "next/head";
import { AlertaProvider } from "./context/AlertaContext";
import RoutesPrivacy from "./hook/useRoutesPrivacy/GlobalHooks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body 
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
        >
              <AuthProvider>
                <CartProvider>
                  <AlertaProvider>
                    <GlobalHooks />
                      {children}
                  </AlertaProvider>
                </CartProvider>
              </AuthProvider>
        </body>
    </html>
  );
}

